<a href="https://colab.research.google.com/github/abdulloyev/DataScientis-openSource/blob/main/%231%20Labaratoriya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Abdulloyev Ulug'bek -- Labaratoriya N1 `NumPy kutubxonasini`**
---

## **1).** NumPy kutubxonasini o‘rnatish va asosiy massivni yaratish.

In [715]:
import numpy as np
list_ = [1, 8, 5, 3, 0]
npArray = np.array(list_)

type(npArray)

numpy.ndarray

In [716]:
npArray

array([1, 8, 5, 3, 0])

## **2).** 0 dan 20 gacha bo‘lgan juft sonlardan iborat massiv yarating

In [717]:
npArray = np.arange(2, 20, 2)
npArray

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## **3).** Ikki o‘lchovli massivlar yaratish va uning shaklini aniqlash.

In [718]:
npArray = np.array([[2, 7, 4], [8, 1, 6]])
npArray.ndim

2

## **4).** np.random.randint() funksiyasidan foydalanib, 1 dan 100 gacha bo‘lgan tasodifiy butun sonlardan iborat 2D massiv yarating.

In [719]:
npArray = np.random.randint(1, 100, size=(3, 2))
npArray

array([[11, 20],
       [10, 72],
       [47, 23]])

## **5).** Elementar matematik funksiyalarni qo‘llash: sin, cos, log.

In [720]:
sin_arr = np.sin(npArray)
sin_arr

array([[-0.99999021,  0.91294525],
       [-0.54402111,  0.25382336],
       [ 0.12357312, -0.8462204 ]])

In [721]:
cos_arr = np.cos(npArray)
cos_arr

array([[ 0.0044257 ,  0.40808206],
       [-0.83907153, -0.96725059],
       [-0.99233547, -0.53283302]])

In [722]:
log_arr = np.log(npArray)
log_arr

array([[2.39789527, 2.99573227],
       [2.30258509, 4.27666612],
       [3.8501476 , 3.13549422]])

## **6).** Massivning bir qismini kesib oling (slicing) va yangi massiv yarating

In [723]:
npArray

array([[11, 20],
       [10, 72],
       [47, 23]])

In [724]:
# 2D keshish
slice_arr = npArray[2:]
slice_arr

array([[47, 23]])

In [725]:
# 1D array keshish
npArray = np.array([2, 5, 7, 8, 3, 7, 2, 6])
slice_arr = npArray[2:5]
slice_arr

array([7, 8, 3])

## **7).** Massivdagi maksimal va minimal qiymatlarni topish.

In [726]:
npArray = np.random.randint(1, 100, size=[2, 4])
npArray.max()

85

In [727]:
npArray.min()

7

## **8).** Massivni sortlash..

In [728]:
npArray.sort()
npArray

array([[ 7, 36, 43, 85],
       [20, 31, 39, 85]])

## **9).** Massivni transpozitsiya qilish (2D massiv uchun).

In [729]:
npArray

array([[ 7, 36, 43, 85],
       [20, 31, 39, 85]])

In [730]:
npArray.reshape([4, 2])

array([[ 7, 36],
       [43, 85],
       [20, 31],
       [39, 85]])

## **10).** Massivning barcha elementlarini kvadratga ko‘taring.

In [731]:
npArray

array([[ 7, 36, 43, 85],
       [20, 31, 39, 85]])

In [732]:
for val in npArray:
  print(val*val)

[  49 1296 1849 7225]
[ 400  961 1521 7225]


## **11).** np.eye() funksiyasidan foydalanib, 4x4 o‘lchamli identifikatsion matritsa (identity matrix) yarating

In [733]:
matritsa = np.eye(4, 4)
matritsa

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## **12).** np.select() funksiyasidan foydalanib, massivda shartlarga ko‘ra qiymatlarni o‘zgartiring (masalan, 5 dan katta bo‘lgan elementlarni 10 ga o‘zgartiring).

In [734]:
npArray # buyerda qiymatlar yuqorida random qilib olindi

array([[ 7, 36, 43, 85],
       [20, 31, 39, 85]])

In [735]:
# shart
conditions = [npArray > 5]

# shartga mos qiymat
choices = [10]

arr = np.select(conditions, choices, default=npArray)

In [736]:
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

## **13).** np.isin() funksiyasidan foydalanib, massivda ma’lum bir qiymatlar mavjudligini tekshiring.

In [737]:
list_ = [2, 3, 6, None, 5]

arr = np.array(list_)
test_v = [2, 5]
np.isin(npArray, test_v)

array([[False, False, False, False],
       [False, False, False, False]])

## **14).** np.isin() funksiyasidan foydalanib, massivda ma’lum bir qiymatlar mavjudligini tekshiring.

In [738]:
list_ = [2, 3, 6, None, 5]

arr = np.array(list_)
test_v = [2, 5]
np.isin(npArray, test_v)

array([[False, False, False, False],
       [False, False, False, False]])

## **15).** `np.array_split()` funksiyasidan foydalanib, massivni 4 ta teng bo‘lmagan qismga bo‘ling


In [739]:
arr = np.arange(0, 16)

res = np.array_split(arr, [2, 8, 14])

# enumerate - 2ta narsa qaytaradi (index, value)
for i, part in enumerate(res):
    print(i+1, part)

1 [0 1]
2 [2 3 4 5 6 7]
3 [ 8  9 10 11 12 13]
4 [14 15]


## **16).** Massivlarni birlashtirish (vstack, hstack).



In [740]:
arr1 = np.arange(0, 4)
arr2 = np.arange(4, 8)

print(arr1)
print(arr2)

[0 1 2 3]
[4 5 6 7]


`vstack` funksiyasi massivlarni **vertikal** (ustma-ust) birlashtiradi.

In [741]:
# ustma ust
res = np.vstack((arr1, arr2))
res

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

`hstack` funksiyasi massivlarni **gorizontal** (yonma-yon) birlashtiradi

In [742]:
# yonma-yon
res = np.hstack((arr1, arr2))
res

array([0, 1, 2, 3, 4, 5, 6, 7])

## **17).** `np.split()` funksiyasidan foydalanib, massivni 3 ta teng qismga bo‘ling.

In [743]:
arr1 = np.arange(0, 11)

res = np.split(arr1, [6])
res[0]

array([0, 1, 2, 3, 4, 5])

In [744]:
res[1]

array([ 6,  7,  8,  9, 10])

## **18).** Yig’indilarni hisoblash: `sum()` funksiyasidan foydalanish.

In [745]:
arr1.sum()

55

## **19).** NumPyda `unique()` va `intersect1d()` funksiyalari.

In [746]:
arr = np.array([2, 5, 3, 2, 7, 2, 9, 5, 3, 8])

# unikal takrorlanman qiymatlar
np.unique(arr)

array([2, 3, 5, 7, 8, 9])

In [747]:
arr1 = np.array([2, 5, 2, 8])
arr2 = np.array([5, 6, 1])

# 2ta arr dagi bor qiymatlar(kesishmasi)
np.intersect1d(arr1, arr2)

array([5])

## **20).** Massivning elementlarini indeks orqali o‘zgartiring (masalan, 3-indeksdagi elementni 10 ga o‘zgartiring)


In [748]:
npArray = np.array([3, 7, 1, 8])

npArray

array([3, 7, 1, 8])

In [749]:
npArray[3] = 10
npArray

array([ 3,  7,  1, 10])

## **21).** 2D massivning bir qatorini yoki ustunini ajratib oling.


In [750]:
d2 = np.array([[4, 5, 6], [8, 2, 5]])
d2

array([[4, 5, 6],
       [8, 2, 5]])

In [751]:
# qator bo'yicha
d2[1, :]

array([8, 2, 5])

In [752]:
# ustun bo'yicha
d2[:, 0]

array([4, 8])

## **22).** `np.reshape()` funksiyasidan foydalanib, 1D massivni 2D massivga o‘zgartiring.


In [753]:
npArray = np.arange(1, 11)

# 1-usul
npArray = np.reshape(npArray, [2, 5])
print(npArray.ndim)
npArray

2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [754]:
# 2-usul
npArray = npArray.reshape(5, 2)
print(npArray.ndim)
npArray

2


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## **23).** `np.concatenate()` funksiyasidan foydalanib, ikki massivni birlashtiring.


In [755]:
print(arr1)
print(arr2)

[2 5 2 8]
[5 6 1]


In [756]:
#ketma-ket
np.concatenate((arr1, arr2), axis=0) # ustma ust qilish uchun axis=1

array([2, 5, 2, 8, 5, 6, 1])

## **24).** `np.where()` funksiyasidan foydalanib, massivda 5 dan katta bo‘lgan elementlarni toping



In [757]:
arr = np.arange(90, 101)
arr

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [758]:
index = np.where(arr >= 95) # bu indexlarni qaytaradi
list_ = arr[index]
list_

array([ 95,  96,  97,  98,  99, 100])

## **25).** Massivning standart og’ishini (standard deviation) hisoblang.



In [759]:
arr

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [760]:
std_dev = np.std(arr)
std_dev

3.1622776601683795